default_language_version:
  node: system
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-json
    - id: check-yaml
    - id: check-case-conflict
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: fix-byte-order-marker
    - id: check-merge-conflict
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
    - id: codespell
      entry: codespell
      args: ['--skip=*.git*,*cdk.out*,*venv*,*mypy_cache*,*package-lock*,*node_modules*,*dist/*,*.[ct]sv,*.xlsx,*.ipynb,*.lock']

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: 'v3.0.3'
  hooks:
    - id: prettier
      name: prettier-md
      files: .*\.(ya?ml|json|md)$
      exclude: ^node_modules/|config.yaml|^dist/

    - id: prettier
      name: prettier-ts
      args: [--write, --config, .prettierrc]
      files: \.(ts|tsx)$
      exclude: ^node_modules/|^dist/

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]

- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
    - id: black
    - id: black-jupyter

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.1.3'
  hooks:
    - id: ruff
      args:
        - --exit-non-zero-on-fix
        - --extend-ignore=E203

- repo: https://github.com/pycqa/flake8
  rev: '6.1.0'
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-docstrings
        - flake8-broken-line
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-debugger
        - flake8-string-format
      args:
        - --docstring-convention=google
        - --max-line-length=120
        - --extend-ignore=E203,E266
      exclude: ^(__init__.py$|.*\/__init__.py$|.*bin\/)


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.6.1'
  hooks:
    - id: mypy
      args:
        - --config-file=pyproject.toml
        - --install-types
        - --non-interactive
        - --exclude=*/test*
      exclude: ^(test|doesitcache)

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: 'v8.53.0'
  hooks:
    - id: eslint
      files: \.[jt]sx?$
      types: [file]
      args:
        - --max-warnings=10
        - --fix
